name: mate_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
#  sdk: '>=3.0.0-218.1.beta <4.0.0'
  sdk: ">=2.18.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  note:

dev_dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1
  test: ^1.21.0
  analyzer: ">=5.0.0 <6.0.0"
  file: ^6.1.4
  code_builder: ^4.4.0
  dart_style: ^2.0.0
  path: ^1.8.3

dependency_overrides:
  note:
    path: ../note
